const users = [
	{
		id: 1,
		name: 'João',
		surname: 'Félix',
		handler: 'jfelix.piw.social',
		photo: '001.jpg',
	},
	{
		id: 2,
		name: 'Jane',
		surname: 'Domingues',
		handler: 'janethevirgin.piw.social',
		photo: '002.jpg',
	},
	{
		id: 3,
		name: 'Juno',
		surname: 'Domingues',
		handler: 'juno.piw.social',
		photo: '003.jpg',
	},
	{
		id: 4,
		name: 'Rafael',
		surname: 'Silva',
		handler: 'rfsilva.piw.social',
		photo: '004.jpg',
	},
	{
		id: 5,
		name: 'Maria Eduarda',
		surname: 'Siqueira',
		handler: 'dudasiqueira.piw.social',
		photo: '005.jpg',
	},
	{
		id: 6,
		name: 'Sílvia',
		surname: 'Santos',
		handler: 'sspobre.piw.social',
		photo: '006.jpg',
	},
	{
		id: 7,
		name: 'Fernanda',
		surname: 'Monte',
		handler: 'montebranco.piw.social',
		photo: '007.jpg',
	},
	{
		id: 8,
		name: 'Jorge',
		surname: 'Guedes',
		handler: 'obscurial.piw.social',
		photo: '008.jpg',
	},
	{
		id: 9,
		name: 'Alberto',
		surname: 'Fernandes',
		handler: 'beto_fernandes.piw.social',
		photo: '009.jpg',
	},
	{
		id: 10,
		name: 'Thiago',
		surname: 'Távora',
		handler: 'thiagotv.piw.social',
		photo: '010.jpg',
	},
	{
		id: 11,
		name: 'Celina',
		surname: 'Batista',
		handler: 'celina.piw.social',
		photo: '011.jpg',
	},
	{
		id: 12,
		name: 'Camila',
		surname: 'Farias',
		handler: 'k1000la.piw.social',
		photo: '012.jpg',
	},
	{
		id: 13,
		name: 'Sérgio',
		surname: 'Torres',
		handler: 'sergiotorres.piw.social',
		photo: '013.jpg',
	},
	{
		id: 14,
		name: 'Bruno',
		surname: 'Silva',
		handler: 'brunosfotos.piw.social',
		photo: '014.jpg',
	},
	{
		id: 15,
		name: 'Jheniffer',
		surname: 'Carvalho',
		handler: 'jkhta.piw.social',
		photo: '015.jpg',
	},
]

export default users
