const users = [
	{
		id: 1,
		name: 'João',
		surname: 'Félix',
		handler: 'jfelix.piw.social',
		photo: '01.jpg',
	},
	{
		id: 2,
		name: 'Jane',
		surname: 'Domingues',
		handler: 'janethevirgin.piw.social',
		photo: '02.jpg',
	},
	{
		id: 3,
		name: 'Juno',
		surname: 'Domingues',
		handler: 'juno.piw.social',
		photo: '03.jpg',
	},
	{
		id: 4,
		name: 'Rafael',
		surname: 'Silva',
		handler: 'rfsilva.piw.social',
		photo: '04.jpg',
	},
	{
		id: 5,
		name: 'Maria Eduarda',
		surname: 'Siqueira',
		handler: 'dudasiqueira.piw.social',
		photo: '05.jpg',
	},
	{
		id: 6,
		name: 'Sílvia',
		surname: 'Santos',
		handler: 'sspobre.piw.social',
		photo: '06.jpg',
	},
	{
		id: 7,
		name: 'Fernanda',
		surname: 'Monte',
		handler: 'montebranco.piw.social',
		photo: '07.jpg',
	},
	{
		id: 8,
		name: 'Jorge',
		surname: 'Guedes',
		handler: 'obscurial.piw.social',
		photo: '08.jpg',
	},
	{
		id: 9,
		name: 'Alberto',
		surname: 'Fernandes',
		handler: 'beto_fernandes.piw.social',
		photo: '09.jpg',
	},
	{
		id: 10,
		name: 'Thiago',
		surname: 'Távora',
		handler: 'thiagotv.piw.social',
		photo: '10.jpg',
	},
	{
		id: 11,
		name: 'Celina',
		surname: 'Batista',
		handler: 'celina.piw.social',
		photo: '11.jpg',
	},
	{
		id: 12,
		name: 'Camila',
		surname: 'Farias',
		handler: 'k1000la.piw.social',
		photo: '12.jpg',
	},
	{
		id: 13,
		name: 'Sérgio',
		surname: 'Torres',
		handler: 'sergiotorres.piw.social',
		photo: '13.jpg',
	},
	{
		id: 14,
		name: 'Bruno',
		surname: 'Silva',
		handler: 'brunosfotos.piw.social',
		photo: '14.jpg',
	},
	{
		id: 15,
		name: 'Jheniffer',
		surname: 'Carvalho',
		handler: 'jkhta.piw.social',
		photo: '15.jpg',
	},
]

export default users
